format = """\
  $directory\
  $custom\
  $git_state\
  $line_break\
  $character\
  """

[directory]
style = "bold white"

[character]
success_symbol = '[→](bold green)'
error_symbol = '[→](bold red)'

[custom.git_simple]
command = "starship-git-simple"
require_repo = true
when = true
ignore_timeout = true
style = ""
