format = """\
  $username\
  $hostname\
  $directory\
  $custom\
  $git_state\
  $line_break\
  $character\
  """

[directory]
style = "bold white"

[custom.git_simple]
command = "starship-git-simple"
require_repo = true
when = true
ignore_timeout = true
style = ""
