# Nerd Fonts nf-seti-coffee \ue61b
format = """\
   $directory\
  $custom\
  $git_state\
  $line_break\
  $character\
  """

[directory]
style = "bold white"
repo_root_style	= "bold"
read_only = "" # Nerd Fonts nf-fa-lock \uf023

[character]
# Nerd Fonts nf-fa-angle_right \f105
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[custom.git_simple]
command = "starship-git-simple"
require_repo = true
when = true
ignore_timeout = true
style = ""
