# Squirrelsong Dark Theme
# https://sapegin.me/squirrelsong/

[colors]
foreground = '#9e8a74'
background = '#352a21'

cursor_bg = '#9e8a74'
cursor_fg = '#352a21'
cursor_border = '#9e8a74'

selection_fg = '#9e8a74'
selection_bg = '#564538'

split = '#4C3E32'

visual_bell = "#db7666"

ansi = [
  '#352a21',
  '#ac493e',
  '#558240',
  '#ceb250',
  '#5d99cb',
  '#7f61b3',
  '#4f9593',
  '#c4a389',
]

brights = [
  '#6b503c',
  '#db7666',
  '#73a15c',
  '#e2c54c',
  '#64a1d3',
  '#a08ac2',
  '#adccc5',
  '#dcd5c0',
]

[colors.tab_bar]
# Retro tab bar
background = '#352a21'
# Fancy tab bar
inactive_tab_edge = '#352a21'

[colors.tab_bar.active_tab]
bg_color = '#574131'
fg_color = '#c4a389'
intensity = 'Bold'

[colors.tab_bar.inactive_tab]
bg_color = '#352a21'
fg_color = '#9e8a74'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#453327'
fg_color = '#c4a389'

[colors.tab_bar.new_tab]
bg_color = '#352a21'
fg_color = '#9e8a74'

[colors.tab_bar.new_tab_hover]
bg_color = '#453327'
fg_color = '#c4a389'

[metadata]
aliases = []
author = 'Artem Sapegin'
name = 'Squirrelsong Dark'
